### ISSUE TITLE
no services

### ISSUE THREAD

**Issue by mathieujobin** [snapcrafters/vault#7]
Hello,

I am running Kubuntu 17.10

I could install vault 0.9.0 via simple `sudo snap install vault`
I upgraded to v0.9.5 using `sudo snap refresh vault --edge`

but I cannot start the service
```
$ sudo snap start vault 
[sudo] password for mathieu: 
error: snap "vault" has no services
$ snap services
Snap  Service  Startup  Current
$
```

I also tried uninstalling and reinstalling with `--dev-mode`

no changes

how do we run the service?

thanks

**Comment by javacruft** [comment]
Well now that's kinda the trick with this snap (and I'm making assumptions about the original thinking so I may be wrong).

Automatically restarting vault on a snap refresh is generally a bad idea; vault daemons must be unsealed using 3/5 key shares for the master key to be unlocked so vault can actually operate.

If the snap actually ran the service, then vault would get automatically restarted on refresh returning in a sealed state, and hence unusable.

**Comment by javacruft** [comment]
Sample systemd unit as used by the vault charm:

  https://github.com/openstack/charm-vault/blob/master/src/templates/vault.service.j2

**Comment by mathieujobin** [comment]
ok, make sense, but maybe it should at least install the service file, the system can take care for starting it.
