### ISSUE TITLE
Update to 0.9.4 for bionic charm support

### ISSUE THREAD

**Issue by stub42** [snapcrafters/vault#8]
We need to get the snap updated to 0.9.4, which we believe supports PostgreSQL 10 (the supported PostgreSQL version under Ubuntu bionic).

**Comment by javacruft** [comment]
0.9.6 is already in the edge channel - I'm also preparing 0.10.0 as well.

**Comment by javacruft** [comment]
Closing this issue as we've been on 1.1.x for a while now
